/**
 * Image Optimization Script for Zaveri Realty
 * - Resizes all JPEGs in public/assets/barsana/ to 1920px width
 * - Generates tiny base64 blur placeholders for each image
 * - Outputs a blurData.ts file for use with Next.js <Image placeholder="blur">
 */

const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const ASSETS_DIR = path.join(__dirname, "..", "public", "assets", "barsana");
const TARGET_WIDTH = 1920;
const BLUR_WIDTH = 20; // tiny placeholder
const OUTPUT_FILE = path.join(__dirname, "..", "data", "blurData.ts");

async function processImages() {
  const files = fs
    .readdirSync(ASSETS_DIR)
    .filter((f) => /\.(jpg|jpeg|png)$/i.test(f))
    .sort();

  console.log(`Found ${files.length} images to process.\n`);

  const blurMap = {};

  for (const file of files) {
    const filePath = path.join(ASSETS_DIR, file);
    const inputBuffer = fs.readFileSync(filePath);
    const metadata = await sharp(inputBuffer).metadata();
    const originalSize = inputBuffer.length;

    console.log(`Processing: ${file} (${metadata.width}x${metadata.height}, ${(originalSize / 1024).toFixed(0)}KB)`);

    // 1. Resize to 1920px width if wider
    let outputBuffer;
    if (metadata.width > TARGET_WIDTH) {
      outputBuffer = await sharp(inputBuffer)
        .resize({ width: TARGET_WIDTH, withoutEnlargement: true })
        .jpeg({ quality: 82, progressive: true, mozjpeg: true })
        .toBuffer();

      const savings = (((originalSize - outputBuffer.length) / originalSize) * 100).toFixed(1);
      console.log(`  ✓ Resized: ${TARGET_WIDTH}px wide, ${(outputBuffer.length / 1024).toFixed(0)}KB (${savings}% smaller)`);
    } else {
      // Still re-compress with mozjpeg for better compression
      outputBuffer = await sharp(inputBuffer)
        .jpeg({ quality: 82, progressive: true, mozjpeg: true })
        .toBuffer();

      console.log(`  ✓ Re-compressed: ${(outputBuffer.length / 1024).toFixed(0)}KB`);
    }

    // Write via temp file to avoid OneDrive lock issues
    const tmpPath = filePath + ".tmp";
    fs.writeFileSync(tmpPath, outputBuffer);
    try {
      fs.unlinkSync(filePath);
    } catch (e) {
      // If unlink fails, try rename which may work
    }
    fs.renameSync(tmpPath, filePath);

    // 2. Generate tiny blur placeholder
    const blurBuffer = await sharp(outputBuffer)
      .resize({ width: BLUR_WIDTH })
      .jpeg({ quality: 30 })
      .toBuffer();

    const base64 = `data:image/jpeg;base64,${blurBuffer.toString("base64")}`;
    const key = `/assets/barsana/${file}`;
    blurMap[key] = base64;
    console.log(`  ✓ Blur placeholder generated (${blurBuffer.length} bytes)\n`);
  }

  // 3. Write blur data map
  const tsContent = `// Auto-generated by scripts/optimize-images.js — do not edit manually
// Provides base64 blur placeholders for Next.js <Image placeholder="blur" blurDataURL={...} />

export const blurDataMap: Record<string, string> = ${JSON.stringify(blurMap, null, 2)};

/**
 * Get blur data URL for a given image path.
 * Falls back to a neutral grey if the image is not in the map.
 */
export function getBlurDataURL(src: string): string {
  return blurDataMap[src] || "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMCwsKCwsKDA0QDAsNEA0KDBAREhMSExQLDhIXFBUSFhESEx//2wBDAQMEBAUEBQkFBQkSDAsMEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhL/wAARCAADAAQDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AKgAB//Z";
}
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent, "utf-8");
  console.log(`✅ Blur data written to: ${OUTPUT_FILE}`);
  console.log(`\nDone! All ${files.length} images optimized.`);
}

processImages().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
